version: "3.9"

services:
  db:
    image: mysql:8.0.43
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # mật khẩu root
      MYSQL_DATABASE: e_commerce # database mặc định
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce123
    ports:
      - "3306:3306"
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
      - db_data:/var/lib/mysql # để dữ liệu không mất khi container restart

volumes:
  db_data:
